pull_request_rules:
  - name: backport to older distros
    conditions:
      - base=dev
    actions:
      backport:
        branches:
          - foxy galactic humble rolling
        assignees:
          - "{{ author }}"
